# This source file is part of the Swift.org open source project
#
# Copyright (c) 2025 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for Swift project authors

blank_issues_enabled: true
contact_links:
  - name: ðŸŒ Discuss an idea
    url: https://forums.swift.org/c/related-projects/swift-testing
    about: >
      Share an idea with the Swift Testing community.
  - name: ðŸ“„ Formally propose a change
    url: https://github.com/swiftlang/swift-testing/blob/main/Documentation/Proposals/0000-proposal-template.md
    about: >
      Formally propose an addition, removal, or change to the APIs or features
      of Swift Testing.
  - name: ðŸ™‹ Ask a question
    url: https://forums.swift.org/c/related-projects/swift-testing
    about: >
      Ask a question about or get help with Swift Testing. Beginner questions
      welcome!
  - name: ðŸª² Report an issue with Swift Package Manager
    url: https://github.com/swiftlang/swift-package-manager/issues/new/choose
    about: >
      Report an issue with Swift Package Manager, which includes the
      "swift test" CLI tool.
  - name: ðŸª² Report an issue with Apple software using Feedback Assistant
    url: https://developer.apple.com/bug-reporting
    about: >
      Report an issue with Xcode or other closed source Apple developer
      software such as XCTest.
  - name: ðŸª² Report an issue with the VS Code Swift plugin
    url: https://github.com/swiftlang/vscode-swift/issues/new/choose
    about: >
      Report an issue with the Swift plugin for VS Code, which integrates with
      Swift Testing.
  - name: ðŸ“– Learn about Swift Testing
    url: https://swiftpackageindex.com/swiftlang/swift-testing/main/documentation/testing
    about: >
      Read the official Swift Testing documentation.
