name: main branch, 6.3 toolchain

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.7
    with:
      linux_swift_versions: '["nightly-6.3"]'
      linux_os_versions: '["amazonlinux2", "jammy"]'
      linux_static_sdk_versions: '["nightly-6.3"]'
      windows_swift_versions: '["nightly-6.3"]'
      enable_macos_checks: true
      macos_xcode_versions: '["26.3", "26.4_beta"]'
      enable_wasm_sdk_build: true
      wasm_sdk_versions: '["nightly-6.3"]'
