name: Pull request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      linux_swift_versions: '["nightly-main", "nightly-6.3"]'
      linux_os_versions: '["amazonlinux2", "jammy"]'
      linux_static_sdk_versions: '["nightly-main"]'
      windows_swift_versions: '["nightly-main", "nightly-6.3"]'
      enable_macos_checks: true
      macos_xcode_versions: '["26.2"]'
      enable_ios_checks: true
      ios_host_xcode_versions: '["26.2"]'
      enable_wasm_sdk_build: true
      wasm_sdk_versions: '["nightly-main", "nightly-6.3"]'
      enable_android_sdk_build: true
      android_ndk_versions: '["r28c"]'
      android_sdk_triples: '["aarch64-unknown-linux-android33", "x86_64-unknown-linux-android28"]'
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.7
    with:
      license_header_check_project_name: "Swift"
      docs_check_enabled: false
      format_check_enabled: false
      api_breakage_check_enabled: false
