name: Pull request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.3
    with:
      linux_swift_versions: '["nightly-main", "nightly-6.3", "nightly-6.2"]'
      linux_os_versions: '["amazonlinux2", "jammy"]'
      windows_swift_versions: '["nightly-main", "nightly-6.3", "nightly-6.2"]'
      enable_macos_checks: true
      macos_exclude_xcode_versions: '[{"xcode_version": "16.2"}, {"xcode_version": "16.3"}, {"xcode_version": "16.4"}]'
      enable_ios_checks: true
      ios_host_exclude_xcode_versions: '[{"xcode_version": "16.2"}, {"xcode_version": "16.3"}, {"xcode_version": "16.4"}]'
      enable_wasm_sdk_build: true
      enable_android_sdk_build: true
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.2
    with:
      license_header_check_project_name: "Swift"
      docs_check_enabled: false
      format_check_enabled: false
      api_breakage_check_enabled: false
